FROM python:3.12-slim

# Minimal system dependencies for networking and common Python libs
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

# Install only the necessary Python libraries for HDFS and Data Science
# pandas and pyarrow are great for reading/writing Parquet/CSV directly to HDFS
RUN pip install --no-cache-dir hdfs pandas pyarrow

# Keep the container alive so you can 'docker exec' into it
CMD ["tail", "-f", "/dev/null"]
